version: '3'
services:
  application-services:
    build: ./devoir/
    volumes:
      - ./devoir/:/src/application/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1